---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lacomd36/public_html
    - export REPOPATH=/home/lacomd36/repos/lacom-dist/
    # Remove previous old files, if any.
    - /bin/rm -Rf ${DEPLOYPATH}_old
    # Copy old site files to another directory.
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    # Copy files to public html (deploy)
    - /bin/cp -Rf ${REPOPATH}/* ${DEPLOYPATH}/
    - /bin/rm -R ${DEPLOYPATH}/.git
